/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PRG381_Milestone2.view;

import PRG381_Milestone2.controller.CounselorController;
import PRG381_Milestone2.model.Counselor;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author 601052
 */
public class CounselorUpdate extends javax.swing.JFrame {

    /**
     * Creates new form CounselorUpdate
     */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        counsName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        counsSpec = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        counsAvail = new javax.swing.JComboBox<>();
        counFormUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 190));

        jLabel9.setText("Name");

        jLabel10.setText("Specialization");

        jLabel11.setText("Available");

        counsAvail.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        counsAvail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                counsAvailActionPerformed(evt);
            }
        });

        counFormUpdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        counFormUpdate.setText("Update");
        counFormUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                counFormUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9)
                            .addComponent(counsName)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(counsSpec)
                            .addComponent(counsAvail, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(counFormUpdate)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(counsName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(counsSpec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(counsAvail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(counFormUpdate)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public class UpdateAppointmentFrame extends javax.swing.JFrame{
        
        private String originalName;
        
        public UpdateAppointmentFrame(String counselorName, String spec, String isAvailable){
            initComponents();
            
            this.originalName = counselorName;
            
            counsName.setText(counselorName);
            counsSpec.setText(spec);
            counsAvail.setSelectedItem(isAvailable);
        }
    }
    
    
    private void counsAvailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_counsAvailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_counsAvailActionPerformed

    private void counFormUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_counFormUpdateActionPerformed
        CounselorController controller = new CounselorController();
        String updatedName = counsName.getText().trim();
        String updatedSpec = counsSpec.getText().trim();
        String updatedAvail = counsAvail.getSelectedItem().toString();

        // validate input
        if (updatedName.isEmpty() || updatedSpec.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            return;
        }

        selectedCounselor.setName(updatedName);
        selectedCounselor.setSpec(updatedSpec);
        selectedCounselor.setAvailable(updatedAvail);

        controller.updateCounselor(selectedCounselor);

        JOptionPane.showMessageDialog(this, "Counselor updated successfully.");

        mainFrame.loadCounselorTable();  

        this.dispose();
    }//GEN-LAST:event_counFormUpdateActionPerformed

    private Counselor selectedCounselor;
    private MainFrame mainFrame;

    public CounselorUpdate(MainFrame mainFrame, Counselor selectedCounselor) {
        initComponents();
        this.mainFrame = mainFrame;
        this.selectedCounselor = selectedCounselor;

        // preload fields
        counsName.setText(selectedCounselor.getName());
        counsSpec.setText(selectedCounselor.getSpec());
        counsAvail.setSelectedItem(selectedCounselor.getAvailable());

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CounselorUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CounselorUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CounselorUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CounselorUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton counFormUpdate;
    private javax.swing.JComboBox<String> counsAvail;
    private javax.swing.JTextField counsName;
    private javax.swing.JTextField counsSpec;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
